using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using System.Threading.Tasks;


namespace TestsGenerator
{
    public class Generator
    {
        private List<string> usings = new List<string>() { 
            "System", 
            "Microsoft.VisualStudio.TestTools.UnitTesting" 
        };

        public string GenerateUnitTestClass(string source)
        {
            var syntaxFactory = SyntaxFactory.CompilationUnit();

            usings.Add(getsNamespaceName(source));
            syntaxFactory = AddUsings(usings, syntaxFactory);

            var @namespace = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(getsNamespaceName(source) + "Test")).NormalizeWhitespace();

            var classDeclaration = SyntaxFactory.ClassDeclaration(getClassName(source) + "Test");

            classDeclaration = classDeclaration.AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword));

            classDeclaration = classDeclaration.WithAttributeLists(
                classDeclaration.AttributeLists.Add(
                    SyntaxFactory.AttributeList(
                        SyntaxFactory.SingletonSeparatedList(
                            SyntaxFactory.Attribute(
                                SyntaxFactory.IdentifierName("TestClass")
                                ).NormalizeWhitespace()
                            )
                        )
                    )
                );

            IEnumerable<MethodDeclarationSyntax> tM = GetMethods(source);
            var testMethods = new List<MemberDeclarationSyntax>();
            foreach (MethodDeclarationSyntax m in tM) {
                var methodDeclaration = AddMethod("void", m.Identifier + "Test");
                testMethods.Add(methodDeclaration);
            }

            classDeclaration = classDeclaration.AddMembers(testMethods.ToArray());

            @namespace = @namespace.AddMembers(classDeclaration);

            syntaxFactory = syntaxFactory.AddMembers(@namespace);

            var code = syntaxFactory
                .NormalizeWhitespace()
                .ToFullString();

            return code;
        }

        public Task<string> GenerateUnitTestClassAsync(string source)
        {
            return Task.Run(() => GenerateUnitTestClass(source));
        }

        private CompilationUnitSyntax AddUsings(List<string> usings, CompilationUnitSyntax CUS)
        {
            foreach (var usingName in usings)
            {
                CUS = CUS.AddUsings(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(usingName)));
            }
            return CUS;
        }

        private IEnumerable<MethodDeclarationSyntax> GetMethods(string source)
        {
            SyntaxTree tree = SyntaxFactory.ParseSyntaxTree(source);

            IEnumerable<MethodDeclarationSyntax> methods = tree
              .GetRoot()
              .DescendantNodes()
              .OfType<MethodDeclarationSyntax>();

            return methods;
        }

        public static string getClassName(string source)
        {
            SyntaxTree tree = SyntaxFactory.ParseSyntaxTree(source);

            ClassDeclarationSyntax className = tree
              .GetRoot()
              .DescendantNodes()
              .OfType<ClassDeclarationSyntax>().First();

            return className.Identifier.ValueText;
        }

        public static string getsNamespaceName(string source)
        {
            SyntaxTree tree = SyntaxFactory.ParseSyntaxTree(source);

            NamespaceDeclarationSyntax NamespaceName = tree
              .GetRoot()
              .DescendantNodes()
              .OfType<NamespaceDeclarationSyntax>().First();

            return NamespaceName.Name.ToString();
        }

        private MethodDeclarationSyntax AddMethod(string returnType, string methodName)
        {
            var syntax = SyntaxFactory.ParseStatement("Assert.Fail(\"Autogenerated\");");
            var methodDeclaration = SyntaxFactory.MethodDeclaration(SyntaxFactory.ParseTypeName(returnType), methodName)
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                .WithBody(SyntaxFactory.Block(syntax));

            methodDeclaration = methodDeclaration.AddAttributeLists(
                SyntaxFactory.AttributeList(
                        SyntaxFactory.SingletonSeparatedList(
                            SyntaxFactory.Attribute(
                                SyntaxFactory.IdentifierName("TestMethod")
                                ).NormalizeWhitespace()
                            )
                        )
                    );
            return methodDeclaration;
        }
    }
}
